/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccView } from './accView';


export interface AccList { 
    /**
     * Data is the org\'s tracked accreditation records, newest first.
     */
    data?: Array<AccView>;
    /**
     * Disclaimer states that statuses are tracked or provider-reported, never a platform assertion of legal or regulatory compliance.
     */
    disclaimer?: string;
}

