/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityRow } from './activityRow';


export interface ActivityOut { 
    /**
     * Data is the change log newest-first: who created, updated or deleted which key, when.
     */
    data?: Array<ActivityRow>;
}

