/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminMe { 
    displayName?: string;
    email?: string;
    isSuperAdmin?: boolean;
    /**
     * IsWhiteLabel marks the admitted NON-super tier: an admin of an enabled white-label tenant org. Mutually exclusive with IsSuperAdmin (the gate lets exactly one tier through). The operator SPA reads it to render the SUBTREE cockpit — the fleet god-view nav (finance/revenue/metrics/o11y/providers) is hidden — while a super sees the whole fleet.
     */
    isWhiteLabel?: boolean;
    name?: string;
    owner?: string;
    /**
     * ScopeOrgs is the caller\'s visible tenant window: empty for a SuperAdmin (means ALL orgs), or the WL tenant\'s own subtree (today the singleton {org}). The SPA threads it through the faceting/drill-down layer so a WL tenant can never widen a filter past their subtree.
     */
    scopeOrgs?: Array<string>;
}

