/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminSummary { 
    /**
     * Qualified is how many referees have made metered spend.
     */
    qualified?: number;
    /**
     * Signup is how many are recorded but not yet qualified.
     */
    signup?: number;
    /**
     * Total is every referral in the directory.
     */
    total?: number;
}

