/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiAiConnResponse { 
    account_label?: string;
    connected?: boolean;
    provider?: string;
    updated_at?: string;
}

