/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiMetrics } from './aiMetrics';


export interface AimetricsOut { 
    data?: AiMetrics;
    msg?: string;
    status?: string;
}

