/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitSource } from './gitSource';
import { EnvVarJSON } from './envVarJSON';
import { ImageView } from './imageView';


export interface AppView { 
    buildType?: string;
    createdAt?: number;
    currentDeploymentId?: string;
    description?: string;
    dockerfile?: string;
    domains?: Array<string>;
    env?: Array<EnvVarJSON>;
    environment?: string;
    health?: string;
    id?: string;
    image?: ImageView;
    name?: string;
    namespace?: string;
    org?: string;
    phase?: string;
    port?: number;
    projectId?: string;
    replicas?: number;
    repo?: GitSource;
    /**
     * \"\"|pending|syncing|ready|failed (secrets.go)
     */
    secretSync?: string;
    /**
     * honest reason when not ready
     */
    secretSyncDetail?: string;
    slug?: string;
    source?: string;
    status?: string;
    /**
     * GiB; absent means stateless
     */
    storageGb?: number;
    updatedAt?: number;
}

