/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthorProgramSummary { 
    /**
     * AccruedCents is the page\'s lifetime royalty accrued, in integer USD cents.
     */
    accruedCents?: number;
    /**
     * Approved is how many are admitted and accruing.
     */
    approved?: number;
    /**
     * Connected is how many of those are enrolled but not yet admitted to earning.
     */
    connected?: number;
    /**
     * PaidCents is what has been RECORDED as paid across the page, in integer USD cents. Recorded, not settled: the money leaves in a human\'s hands.
     */
    paidCents?: number;
    /**
     * PendingCents is what the platform still owes across the page, in integer USD cents — the sum of each author\'s own accrued − paid, each floored at zero.
     */
    pendingCents?: number;
    /**
     * Suspended is how many have been stopped from accruing further. An author holds exactly one status, so the three buckets never overlap and connected + approved + suspended = total.
     */
    suspended?: number;
    /**
     * Total is how many author records this response actually carried. The roll-up is folded over the SAME page as authors — newest first, bounded by limit (default 500, ceiling 1000) — so on a program larger than the page it summarizes that page, not the fleet.
     */
    total?: number;
}

