/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BackfillResult { 
    /**
     * Forced is true when the caller overrode the already-populated guard.
     */
    forced?: boolean;
    /**
     * SeededBefore is the RFC3339 upper bound the seed actually used.
     */
    seededBefore?: string;
    /**
     * Status is \"ok\" — a seed that did not run answered an error instead.
     */
    status?: string;
}

