/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RateCard } from './rateCard';


export interface BlueprintHealth { 
    /**
     * Blueprints is how many blueprints this build has embedded and priced.
     */
    blueprints?: number;
    /**
     * RateCard is the rate card actually in force after the operator env overlay (CLOUD_BLUEPRINT_UCPU_HR / CLOUD_BLUEPRINT_UGB_HR), not the shipped default.
     */
    rateCard?: RateCard;
    /**
     * Service names the subsystem answering — always \"blueprint\".
     */
    service?: string;
    /**
     * Status is \"ok\"; the route answers 200 whenever the subsystem is mounted.
     */
    status?: string;
}

