/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BotMember { 
    /**
     * Active is whether the agent projects as a LIVE space member, derived from its registry status: empty, \"active\" and \"ready\" are live, anything else (archived/retired) is not. An inactive bot drops out of the roster while its past authorship survives.
     */
    active?: boolean;
    /**
     * ID is the agent id.
     */
    id?: string;
    /**
     * Name is the display name.
     */
    name?: string;
    /**
     * PersonRef is the projected Person _id.
     */
    personRef?: string;
    /**
     * UserID is the derived member account uuid (personUuid).
     */
    userId?: string;
}

