/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BotMember } from './botMember';


export interface BotRoster { 
    /**
     * Bots is every agent of the caller\'s org, projected as a space member.
     */
    bots?: Array<BotMember>;
}

