/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuildSummary { 
    agent?: string;
    endedAt?: string;
    org?: string;
    project?: string;
    repo?: string;
    session?: string;
    startedAt?: string;
    status?: string;
    title?: string;
    turns?: number;
}

