/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuildRow { 
    /**
     * Commit is the short git ref the build pinned.
     */
    commit?: string;
    /**
     * Duration is the wall time of a TERMINAL build; empty while it still runs.
     */
    duration?: string;
    /**
     * ID is the build record\'s id.
     */
    id?: string;
    /**
     * Repo is the repo the build built, or the image it produced.
     */
    repo?: string;
    /**
     * StartedAt is when the build was recorded, RFC3339 UTC.
     */
    startedAt?: string;
    /**
     * Status is the build\'s real state: queued, building, succeeded or failed.
     */
    status?: string;
}

