/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CaptableHolding { 
    /**
     * FullyDiluted is shares plus options.
     */
    fullyDiluted?: number;
    /**
     * Name is the stakeholder\'s name.
     */
    name?: string;
    /**
     * Options is the shares under this stakeholder\'s non-terminal option grants.
     */
    options?: number;
    /**
     * OwnershipPct is fullyDiluted as a percentage of the company\'s fullyDilutedShares, rounded to two decimals; 0 when nothing is issued.
     */
    ownershipPct?: number;
    /**
     * Shares is the shares this stakeholder holds by certificate.
     */
    shares?: number;
    /**
     * StakeholderID is the stakeholder.
     */
    stakeholderId?: string;
}

