/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CaptableCompany { 
    /**
     * CreatedAt is when the company row was seeded, in unix milliseconds.
     */
    createdAt?: number;
    /**
     * ID is the company id, which is the tenant\'s own org id.
     */
    id?: string;
    /**
     * IncorporationCountry is the ISO country the entity is incorporated in.
     */
    incorporationCountry?: string;
    /**
     * IncorporationState is the state or province of incorporation.
     */
    incorporationState?: string;
    /**
     * IncorporationType is the entity kind, e.g. LLC or C_CORP.
     */
    incorporationType?: string;
    /**
     * Name is the company\'s legal name.
     */
    name?: string;
    /**
     * PublicID is the company\'s shareable public identifier.
     */
    publicId?: string;
    /**
     * UpdatedAt is when the company row last changed, in unix milliseconds.
     */
    updatedAt?: number;
}

