/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpanBody } from './spanBody';
import { ClipBody } from './clipBody';
import { MetricBody } from './metricBody';
import { LogBody } from './logBody';
import { Exception } from './exception';
import { UTM } from './uTM';


export interface CaptureEvent { 
    anonymousId?: string;
    channel?: string;
    clip?: ClipBody;
    currency?: string;
    distinctId?: string;
    environment?: string;
    error?: Exception;
    event?: string;
    groupId?: string;
    groupType?: string;
    kind?: string;
    level?: string;
    library?: string;
    libraryVersion?: string;
    log?: LogBody;
    messageId?: string;
    metric?: MetricBody;
    path?: string;
    personId?: string;
    product?: string;
    productId?: string;
    properties?: { [key: string]: any; };
    quantity?: number;
    refCode?: string;
    referrer?: string;
    release?: string;
    resource?: string;
    revenue?: number;
    service?: string;
    sessionId?: string;
    signupWeek?: string;
    site?: string;
    span?: SpanBody;
    spanId?: string;
    timestamp?: string;
    traceId?: string;
    type?: string;
    url?: string;
    utm?: UTM;
}

