/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CaptureEvent } from './captureEvent';


export interface CaptureBatch { 
    batch?: Array<CaptureEvent>;
    events?: Array<CaptureEvent>;
}

