/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartItem } from './cartItem';


export interface Cart { 
    /**
     * CreatedAt is when the cart was opened, RFC3339.
     */
    createdAt?: string;
    /**
     * Currency is the ISO 4217 code every amount below is denominated in.
     */
    currency?: string;
    /**
     * DiscountCents is what coupons and promotions took off, in whole cents.
     */
    discountCents?: number;
    /**
     * Email is the shopper\'s address, when the cart carries one.
     */
    email?: string;
    /**
     * ID is the cart\'s id — what every other cart op addresses it by, and what a storefront persists against the browser session.
     */
    id?: string;
    /**
     * Items are the cart\'s lines, in the order they were added.
     */
    items?: Array<CartItem>;
    /**
     * LineTotalCents is the sum of the lines before any discount, in whole cents.
     */
    lineTotalCents?: number;
    /**
     * Order is the order this cart became, once checkout completed it. Empty until then, and its presence is what makes a cart final.
     */
    order?: string;
    /**
     * ShippingCents is the shipping charge, in whole cents. It stays zero until a shipping option is priced at checkout.
     */
    shippingCents?: number;
    /**
     * Status is \"active\" for a cart still being filled, \"ordered\" once checkout turned it into an order, and \"discarded\" when the shopper abandoned it.
     */
    status?: string;
    /**
     * Store is the storefront the cart is being filled on.
     */
    store?: string;
    /**
     * SubtotalCents is LineTotalCents less DiscountCents, in whole cents.
     */
    subtotalCents?: number;
    /**
     * TaxCents is the sales tax, in whole cents. It stays zero until checkout resolves the shopper\'s tax region.
     */
    taxCents?: number;
    /**
     * TotalCents is what the shopper pays: subtotal plus shipping plus tax, in whole cents.
     */
    totalCents?: number;
    /**
     * UpdatedAt is when the cart was last amended, RFC3339.
     */
    updatedAt?: string;
    /**
     * User is the signed-in shopper this cart belongs to, empty for a guest cart.
     */
    user?: string;
}

