/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Channel } from './channel';


export interface ChannelList { 
    /**
     * Data is every social channel the caller\'s org has connected, disabled ones included (Disabled says which).
     */
    data?: Array<Channel>;
}

