/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChannelAgentsPut { 
    /**
     * Channel is the transport to edit. Required; an unknown value is a 404.
     */
    channel?: string;
    /**
     * Default sets the agent for rooms with no binding of their own; \"hanzo\" restores the built-in. Empty or absent leaves it unchanged.
     */
    'default'?: string;
    /**
     * Rooms binds platform room ids to agents; rooms not named are left alone.
     */
    rooms?: { [key: string]: string; };
    /**
     * Unbind removes the bindings of these rooms, so they fall back to Default.
     */
    unbind?: Array<string>;
}

