/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Charge { 
    /**
     * AmountCents is what this line costs.
     */
    amountCents?: number;
    /**
     * AsOf is when a pass-through amount was last checked against its source.
     */
    asOf?: string;
    /**
     * Code names the line so a caller can branch on it without reading prose.
     */
    code?: string;
    /**
     * Label is what the payer sees on the invoice.
     */
    label?: string;
    /**
     * PassThrough marks money we collect and remit rather than keep — the state\'s fee is not our revenue, and a quote that hides that is a quote that reads as a bigger margin than it is.
     */
    passThrough?: boolean;
    /**
     * Recurring marks a line that repeats. An agent of record is billed every year for as long as the entity stands, and a payer agreeing to a one-time total is not agreeing to that.
     */
    recurring?: string;
    /**
     * Source names who publishes this amount, for a line we merely pass through. Empty for a price of ours, which needs no external authority.
     */
    source?: string;
    /**
     * Stale reports that AsOf is older than the review window — the figure may have moved and nobody has looked. It does not block; it tells.
     */
    stale?: boolean;
}

