/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClickRequest { 
    /**
     * Code is the share-link code that was clicked. Body-only: the URL cannot supply it.
     */
    code?: string;
}

