/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CommitJSON { 
    /**
     * AuthorEmail is the commit author\'s email.
     */
    authorEmail?: string;
    /**
     * AuthorName is the commit author\'s name.
     */
    authorName?: string;
    /**
     * Date is the author date, RFC 3339 UTC.
     */
    date?: string;
    /**
     * Message is the commit\'s SUBJECT — its first line only.
     */
    message?: string;
    /**
     * SHA is the full commit hash.
     */
    sha?: string;
    /**
     * ShortSHA is the abbreviated hash a UI displays.
     */
    shortSha?: string;
}

