/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConnectionOut { 
    /**
     * Account names the connected external account, when the provider reports one.
     */
    account?: string;
    /**
     * Provider is the connector this answer is about.
     */
    provider?: string;
    /**
     * Status is the connection state: connected or disconnected.
     */
    status?: string;
}

