/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ControlCommandView } from './controlCommandView';


export interface ControlDrain { 
    /**
     * Commands is the session\'s control commands newer than the cursor, oldest first.
     */
    commands?: Array<ControlCommandView>;
    /**
     * Cursor is the seq to send as `after` on the next poll — the highest seq in this page, or the cursor sent in when the page is empty.
     */
    cursor?: number;
}

