/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceRequests } from './resourceRequests';


export interface ContainerDetail { 
    image?: string;
    name?: string;
    resources?: ResourceRequests;
}

