/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Count { 
    chatCount?: number;
    currency?: string;
    date?: string;
    messageCount?: number;
    price?: number;
    tokenCount?: number;
    userCount?: number;
}

