/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoverRow { 
    /**
     * Automated is how many clauses have an automated control behind them that something can fail on behalf of.
     */
    automated?: number;
    /**
     * Edition is which edition the clause list is taken from.
     */
    edition?: string;
    /**
     * Framework is the framework id — \"soc2\", \"iso27001\", \"nist80053\".
     */
    framework?: string;
    /**
     * Name is the published standard\'s name.
     */
    name?: string;
    /**
     * None is how many have nothing behind them. It stays visible rather than dropping out of the fraction.
     */
    none?: number;
    /**
     * Note is what the clause list itself is scoped to, when the framework\'s catalog says something a count alone would misrepresent.
     */
    note?: string;
    /**
     * Partial is how many are answered in part.
     */
    partial?: number;
    /**
     * Publisher is who publishes it — AICPA, ISO/IEC, NIST.
     */
    publisher?: string;
    /**
     * Statement is the counts as one sentence, carrying the unit.
     */
    statement?: string;
    /**
     * Total is the framework\'s WHOLE published clause list — the denominator. Counting only the clauses some control happened to name would report 100% every time.
     */
    total?: number;
    /**
     * Unit is what ONE clause is — \"criterion\", \"control\", \"family\". A count without its unit is not a fact, so it travels with every number here.
     */
    unit?: string;
    /**
     * Units is the plural of Unit, for rendering a sentence.
     */
    units?: string;
}

