/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditEntry } from './creditEntry';


export interface CreditBalance { 
    balances?: Array<CreditEntry>;
    userId?: string;
}

