/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConnView } from './connView';


export interface CredentialOut { 
    /**
     * Connected is always true — a failed verification is a 400 and stores nothing.
     */
    connected?: boolean;
    /**
     * Connection is the connector as it now stands.
     */
    connector?: ConnView;
}

