/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CryptoDeposit { 
    addressTag?: string;
    chain?: string;
    depositAddress?: string;
    expiresAt?: string;
    id?: string;
    status?: string;
    token?: string;
}

