/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsageWindowView } from './usageWindowView';


export interface DashResp { 
    /**
     * Account is the linked account that was asked about, when one was named.
     */
    account?: string;
    /**
     * Available is false when the warehouse could not be read. That means \"no answer\", NOT \"no usage\" — the two lists below are then empty for a reason.
     */
    available?: boolean;
    /**
     * Current is the newest window instance of each lane — the dash headline.
     */
    current?: Array<UsageWindowView>;
    /**
     * From is the inclusive start of that window, RFC3339 UTC.
     */
    from?: string;
    /**
     * Provider is the upstream that was asked about, echoed back.
     */
    provider?: string;
    /**
     * Range is the window that was served: 1h, 24h, 7d or 30d.
     */
    range?: string;
    /**
     * Scope says whose rows these are: the caller\'s own linked accounts.
     */
    scope?: string;
    /**
     * Source names the meter of record — the provider\'s own login, not Hanzo.
     */
    source?: string;
    /**
     * To is the exclusive end of that window, RFC3339 UTC.
     */
    to?: string;
    /**
     * Windows is every instance in range, newest first — the history behind it.
     */
    windows?: Array<UsageWindowView>;
}

