/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataroomLiveness { 
    /**
     * Service names the subsystem answering, so a probe response is attributable when several are collected together.
     */
    service?: string;
    /**
     * Status is `ok`. This probe has no degraded answer by design: it reports process liveness and nothing that could be false while the process serves.
     */
    status?: string;
}

