/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataroomPageStat } from './dataroomPageStat';


export interface DataroomLinkStats { 
    /**
     * LinkId is the link these counts are for.
     */
    linkId?: string;
    /**
     * Pages is the per-page breakdown, in page order.
     */
    pages?: Array<DataroomPageStat>;
    /**
     * TotalPageViews is how many page views the link received.
     */
    totalPageViews?: number;
    /**
     * TotalViews is how many viewing sessions the link opened.
     */
    totalViews?: number;
}

