/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DestinationField { 
    /**
     * a sample value of the right shape (\"G-XXXXXXX\"), when one helps
     */
    example?: string;
    /**
     * the camelCase key on both the connect body and the stored config
     */
    key?: string;
    /**
     * human label for the console card\'s input
     */
    label?: string;
    /**
     * when true, a connect that leaves it empty is refused 400
     */
    required?: boolean;
}

