/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Detachment { 
    /**
     * Deleted is whether the method was actually removed. False with no error means it was already gone, which is a successful detach rather than a failure — a retry must not be an error.
     */
    deleted?: boolean;
    /**
     * ID is the method that was detached, echoed so a caller batching several can tell the answers apart.
     */
    id?: string;
}

