/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocPerm { 
    cancel?: boolean;
    create?: boolean;
    'delete'?: boolean;
    read?: boolean;
    role?: string;
    submit?: boolean;
    write?: boolean;
}

