/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocPerm } from './docPerm';
import { DocField } from './docField';


export interface DocType { 
    autoname?: string;
    createdAt?: number;
    fields?: Array<DocField>;
    isSingle?: boolean;
    isSubmittable?: boolean;
    module?: string;
    name?: string;
    permissions?: Array<DocPerm>;
    titleField?: string;
    updatedAt?: number;
}

