/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocType } from './docType';


export interface DocTypeList { 
    /**
     * Data is every DocType defined in the caller\'s org.
     */
    data?: Array<DocType>;
}

