/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentView { 
    /**
     * Body is the rendered document. It is sealed at rest and returned only to the owning org. When the template is counsel-review it opens with the counsel notice, which the engine prepends and no caller can suppress.
     */
    body?: string;
    category?: string;
    /**
     * ContentType is the rendered body\'s media type — text/markdown.
     */
    contentType?: string;
    createdAt?: number;
    esignProvider?: string;
    id?: string;
    signedAt?: number;
    status?: string;
    templateId?: string;
    templateVersion?: number;
    title?: string;
    updatedAt?: number;
}

