/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DriftTally { 
    /**
     * OK is how many rows run what they declare.
     */
    ok?: number;
    /**
     * Red is how many have drifted badly.
     */
    red?: number;
    /**
     * Yellow is how many have drifted within tolerance.
     */
    yellow?: number;
}

