/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DriftFlag { 
    /**
     * Kind is which finding this is, one of stale, un-rolled, floating-declared, floating-running, no-release or zero-assets. It is what code matches on, and the kinds are independent — one row can carry several at once.
     */
    kind?: string;
    /**
     * Message is the finding in words, naming the tags that produced it (\"running v1.2.3 has not rolled to declared v1.2.4\"). For display: match on Kind.
     */
    message?: string;
    /**
     * Severity is this ONE finding\'s weight — yellow for stale and un-rolled, red for the other four. It is a constant of the kind (severityOf), never a judgement about the row, so the same kind always weighs the same.
     */
    severity?: string;
}

