/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Durable { 
    /**
     * Ack is the acknowledgment policy: explicit (default), all, or none.
     */
    ack_policy?: string;
    /**
     * AckWait is how long the broker waits for an ack before redelivering, e.g. \"30s\" (default).
     */
    ack_wait?: string;
    /**
     * Deliver is where delivery starts: all (default), last, new, by_start_sequence, by_start_time, or last_per_subject.
     */
    deliver_policy?: string;
    /**
     * Description says what this consumer is for.
     */
    description?: string;
    /**
     * Name is the durable consumer name (alphanumeric, hyphens, underscores).
     */
    durable_name?: string;
    /**
     * Filter delivers only messages on this org-relative subject (wildcards supported).
     */
    filter_subject?: string;
    /**
     * MaxAckPending caps unacknowledged messages in flight (default 1000).
     */
    max_ack_pending?: number;
    /**
     * MaxDeliver caps delivery attempts per message; -1 (default) is unlimited.
     */
    max_deliver?: number;
    /**
     * StartSeq is the starting sequence for deliver_policy by_start_sequence.
     */
    opt_start_seq?: number;
    /**
     * StartTime is the starting instant for deliver_policy by_start_time.
     */
    opt_start_time?: string;
    /**
     * Replay is the replay pacing: instant (default) or original.
     */
    replay_policy?: string;
}

