/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EndIn { 
    /**
     * ID is the sandbox whose lease ends, from an earlier lease.
     */
    id?: string;
    /**
     * Purge deletes the project\'s DISK as well. It is opt-in because the disk holds the only copy of the checkout: ending a lease is cheap and reversible, deleting someone\'s uncommitted work is neither.
     */
    purge?: boolean;
}

