/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Endpoint { 
    created?: string;
    /**
     * Deliveries7d / Failures7d are cheap usage counters computed from the delivery log over usageWindow (not stored columns) and populated ONLY on list/get. They are 0 when there is no delivery history — never omitempty, so the console always sees them.
     */
    deliveries7d?: number;
    description?: string;
    events?: Array<string>;
    failures7d?: number;
    id?: string;
    org?: string;
    secret?: string;
    status?: string;
    updated?: string;
    url?: string;
}

