/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EngineStatus { 
    /**
     * Reachable is true when the engine answered its health probe.
     */
    reachable?: boolean;
    /**
     * Revision is the engine build\'s git revision, present only when reachable (the server\'s own build identity — it publishes no semver).
     */
    revision?: string;
}

