/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EsignFieldIn { 
    fieldMeta?: any | null;
    height?: any | null;
    page?: any | null;
    positionX?: any | null;
    positionY?: any | null;
    recipientId?: any | null;
    type?: any | null;
    width?: any | null;
}

