/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EsignRecipient } from './esignRecipient';
import { EsignField } from './esignField';


export interface EsignDocument { 
    /**
     * CompletedAt is when the document sealed, in unix milliseconds; null until it does.
     */
    completedAt?: number;
    /**
     * CreatedAt is when the document was uploaded, in unix milliseconds.
     */
    createdAt?: number;
    /**
     * ExternalID is the caller\'s own identifier for this document, echoed back as it was given; null when none was.
     */
    externalId?: string;
    /**
     * Fields is every field on the document, ordered by page and then by when it was placed.
     */
    fields?: Array<EsignField>;
    /**
     * ID is the document id.
     */
    id?: string;
    /**
     * Message is the covering message stored with the document; null when none was given. Nothing in this surface sends it.
     */
    message?: string;
    /**
     * Recipients is everyone on the document, ordered by signing order and then by when they were added — which is also the order a SEQUENTIAL document enforces.
     */
    recipients?: Array<EsignRecipient>;
    /**
     * SigningOrder is PARALLEL or SEQUENTIAL, fixed when the document was created.
     */
    signingOrder?: string;
    /**
     * Source is how the document came to exist. It is DOCUMENT for everything this surface creates.
     */
    source?: string;
    /**
     * Status is DRAFT while recipients and fields may still be added, PENDING once it has gone out, then COMPLETED when every signer has finished or REJECTED if any one of them declined.
     */
    status?: string;
    /**
     * Subject is the covering subject line stored with the document; null when none was given.
     */
    subject?: string;
    /**
     * Title is the document\'s name, and the stem of the download filename.
     */
    title?: string;
    /**
     * UpdatedAt is when the document last changed, in unix milliseconds.
     */
    updatedAt?: number;
}

