/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EsignPlacement { 
    /**
     * ID is the new field\'s id.
     */
    id?: string;
    /**
     * Page is the page it was placed on.
     */
    page?: number;
    /**
     * RecipientID is who must fill it.
     */
    recipientId?: string;
    /**
     * Type is what it collects.
     */
    type?: string;
}

