/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sample } from './sample';
import { UsageLine } from './usageLine';


export interface FinanceUsageView { 
    currency?: string;
    end?: string;
    lines?: Array<UsageLine>;
    series?: Array<Sample>;
    start?: string;
    totalCents?: number;
}

