/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FleetUnit } from './fleetUnit';


export interface FleetBoard { 
    /**
     * Units is the union across sources — agent run-targets, BYO workers, BYO clusters and Visor machines — each row naming the source it came from.
     */
    units?: Array<FleetUnit>;
}

