/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Video } from './video';


export interface GetAiVideos200Response { 
    data?: Array<Video>;
    data2?: any | null;
    /**
     * Empty on success, the reason on failure.
     */
    msg: string;
    status: GetAiVideos200Response.StatusEnum;
}
export namespace GetAiVideos200Response {
    export const StatusEnum = {
        Ok: 'ok',
        Error: 'error'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


