/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Session } from './session';


export interface GetAiSigninSessions200Response { 
    data?: Array<Session>;
    data2?: any | null;
    /**
     * Empty on success, the reason on failure.
     */
    msg: string;
    status: GetAiSigninSessions200Response.StatusEnum;
}
export namespace GetAiSigninSessions200Response {
    export const StatusEnum = {
        Ok: 'ok',
        Error: 'error'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


