/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GithubPagesUpdatedOut { 
    /**
     * Repo is the repository that was updated.
     */
    repo?: string;
    /**
     * Updated is always true — a failure is an HTTP error, never this shape.
     */
    updated?: boolean;
}

