/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitlabProjectView } from './gitlabProjectView';


export interface GitlabProjectsOut { 
    /**
     * Account is the connected GitLab username, so a client can label the list without a second call. Empty when the connection recorded none.
     */
    account?: string;
    /**
     * Projects is every project the token reaches, newest activity first. Never null; [] when the account has none.
     */
    projects?: Array<GitlabProjectView>;
}

