/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitOpsOperation { 
    finishedAt?: string;
    message?: string;
    phase?: string;
    revision?: string;
    startedAt?: string;
}

