/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GrantIn { 
    /**
     * AmountCents is the credit, in whole cents. Must be positive and within the per-grant cap.
     */
    amountCents?: number;
    /**
     * Currency is the ISO code, lower-cased. Empty means usd.
     */
    currency?: string;
    /**
     * Org is the tenant to credit. Required.
     */
    org?: string;
    /**
     * Reason is the operator\'s justification, recorded on the audit row.
     */
    reason?: string;
    /**
     * Source is the money bucket: \"trial\" (default) for a non-cash comp that is never refundable, or \"prepaid\" for real money. Anything unknown falls back to trial.
     */
    source?: string;
    /**
     * User optionally names a MEMBER to credit, by bare IAM username. Empty credits the org. Which of the two the money actually lands on is decided by account.Payer, not here: a pooled org keeps one balance whatever is named.
     */
    user?: string;
}

