/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Graph { 
    category?: string;
    createdTime?: string;
    density?: number;
    displayName?: string;
    endTime?: string;
    errorText?: string;
    layout?: string;
    name?: string;
    owner?: string;
    startTime?: string;
    store?: string;
    text?: string;
}

