/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GraphAssertOut { 
    /**
     * Duplicate is how many members this plane already held. A redelivery collides on its content address and is counted here, not refused: it is the success a retrying caller depends on.
     */
    duplicate?: number;
    /**
     * Reasons names why each refused member was refused, in the order sent.
     */
    reasons?: Array<string>;
    /**
     * Recorded is how many members became new rows.
     */
    recorded?: number;
    /**
     * Refused is how many members were turned away on arrival, before the store was touched — a missing entity, a timestamp that is not RFC 3339, a confidence outside [0,1]. The rest of the batch was still recorded.
     */
    refused?: number;
}

