/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GraphNode { 
    /**
     * \"<doctype>:<name>\" — globally unique, click-to-open key
     */
    id?: string;
    /**
     * the document name (empty for synthetic nodes)
     */
    name?: string;
    project?: string;
    /**
     * display label
     */
    title?: string;
    /**
     * kb-page | kb-memory | kb-source | kb-connector | unresolved
     */
    type?: string;
}

