/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IamCert } from './iamCert';


export interface IamCertsListOutput { 
    certs?: Array<IamCert>;
    total?: number;
}

