/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IamSession { 
    application?: string;
    createdAt?: string;
    createdTime?: string;
    deleted?: boolean;
    /**
     * ExclusiveSignin is a transient control flag (v1 xorm:\"-\"): a caller sets it on a create to collapse SessionId down to the single incoming cookie instead of appending. It is never stored — a persisted session always carries it false, so orm:\"-\" keeps it off the column backends and omitempty keeps it out of the SQLite JSON blob.
     */
    exclusiveSignin?: boolean;
    id?: string;
    name?: string;
    owner?: string;
    sessionId?: Array<string>;
    updatedAt?: string;
}

