/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IamWorkspace } from './iamWorkspace';


export interface IamWorkspacesListOutput { 
    total?: number;
    workspaces?: Array<IamWorkspace>;
}

