/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Formation } from './formation';


export interface ImportCapTableOut { 
    /**
     * Formation is the org\'s incorporation record, now marked cap-table-imported.
     */
    formation?: Formation;
    /**
     * Rows is how many rows were read from the sheet, header included.
     */
    rows?: number;
    /**
     * StakeholdersImported is how many stakeholders the cap table accepted.
     */
    stakeholdersImported?: number;
}

