/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IngressStatus { 
    /**
     * ACMECacheDir is where autocert persists accounts and certificates.
     */
    acmeCacheDir?: string;
    /**
     * ACMEStaging is true when certificates are issued from Let\'s Encrypt staging.
     */
    acmeStaging?: boolean;
    /**
     * EdgeEnabled is true when the edge listeners are actually bound.
     */
    edgeEnabled?: boolean;
    /**
     * HTTPAddr is the address the ACME HTTP-01 + HTTP router listens on.
     */
    httpAddr?: string;
    /**
     * HTTPSAddr is the address the SNI TLS terminator listens on.
     */
    httpsAddr?: string;
    /**
     * LiveHosts is how many hosts the compiled table routes.
     */
    liveHosts?: number;
    /**
     * Proxy names the reverse-proxy implementation behind every route.
     */
    proxy?: string;
    /**
     * Role is \"edge\" when CLOUD_INGRESS_EDGE_ENABLED is set, else \"app\".
     */
    role?: string;
    /**
     * TLSHosts is how many hosts the ACME HostPolicy will issue a certificate for. NOT a subset of LiveHosts: an extraHost owns no route, and a TLS route naming a missing service is skipped while its host still wants a cert.
     */
    tlsHosts?: number;
}

