/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemView } from './itemView';


export interface ItemList { 
    /**
     * Data is the examples of the one dataset named in the path, archived ones included, so the caller sees the whole set rather than what a run would use.
     */
    data?: Array<ItemView>;
}

