/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KbSyncOut { 
    /**
     * Ingested is how many documents landed in the org\'s knowledge store.
     */
    ingested?: number;
    /**
     * Provider is the connector that was pulled.
     */
    provider?: string;
}

