/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormItem } from './formItem';


export interface Layout { 
    category?: string;
    createdTime?: string;
    displayName?: string;
    formItems?: Array<FormItem>;
    name?: string;
    owner?: string;
    position?: string;
    tag?: string;
    type?: string;
    url?: string;
}

