/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LicensingFingerprintResponse { 
    /**
     * Fingerprint is the OPAQUE binding value to pass to POST /v1/licensing/issue. It is one-way: the raw signals cannot be recovered from it and are never echoed back.
     */
    fingerprint?: string;
    /**
     * Version is the binding algorithm revision, so a stored fingerprint stays recognizable across a recipe rotation.
     */
    version?: string;
}

