/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicensingRevocationEntry } from './licensingRevocationEntry';


export interface LicensingRevokeResponse { 
    /**
     * Entry is the stored revocation, including who recorded it and when.
     */
    entry?: LicensingRevocationEntry;
    /**
     * Revoked is always true — a failure is an error status, not a false here.
     */
    revoked?: boolean;
}

