/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LicensingJWK { 
    /**
     * Crv is always \"Ed25519\".
     */
    crv?: string;
    /**
     * Kty is always \"OKP\".
     */
    kty?: string;
    /**
     * Use is always \"sig\".
     */
    use?: string;
    /**
     * X is the public key, base64url (the JWK convention).
     */
    x?: string;
}

