/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarketItem } from './marketItem';


export interface MarketCatalog { 
    /**
     * Items is every capability the caller can see in their own (org, project), each carrying any public listing\'s shop metadata and whether it is installed.
     */
    items?: Array<MarketItem>;
}

