/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MCPListing } from './mCPListing';


export interface McpCatalog { 
    /**
     * Catalog is this page of listings, featured first, then by name.
     */
    catalog?: Array<MCPListing>;
    /**
     * Limit is the page size that was actually applied — the default or the clamp, when the request asked for neither or for too much.
     */
    limit?: number;
    /**
     * Offset is where this page started, so a caller pages from what the server did rather than from what it asked for.
     */
    offset?: number;
    /**
     * Total is how many listings the filter matched, which is more than this page holds whenever there is a next one.
     */
    total?: number;
}

