/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MirrorTargetView { 
    /**
     * CreatedAt is RFC 3339 UTC.
     */
    createdAt?: string;
    /**
     * Host is the target\'s lowercased hostname, taken from URL and never the body.
     */
    host?: string;
    /**
     * ID is the target\'s identifier (\"mir_…\"), the handle to remove it by.
     */
    id?: string;
    /**
     * Repo is the repo whose advanced refs are pushed downstream.
     */
    repo?: string;
    /**
     * URL is the canonical https remote, with any embedded credentials stripped.
     */
    url?: string;
}

