/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MoneyCredits { 
    consumedCents?: number;
    grantedCents?: number;
    /**
     * real money added
     */
    grantedPrepaidCents?: number;
    /**
     * non-cash comps/promos
     */
    grantedTrialCents?: number;
    grants?: number;
    outstandingCents?: number;
}

