/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NewIssue { 
    /**
     * Description becomes the issue body.
     */
    description?: string;
    /**
     * Key is the board — the repository name, from the path.
     */
    key?: string;
    /**
     * Priority is one of none, urgent, high, medium or low.
     */
    priority?: string;
    /**
     * Status is the board column to open into: backlog, todo, in_progress, done or canceled. Empty opens into backlog.
     */
    status?: string;
    /**
     * Title is required.
     */
    title?: string;
}

