/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotifyHealth { 
    /**
     * Service names the subsystem answering — always \"notify\".
     */
    service?: string;
    /**
     * Status is \"ok\"; the route answers 200 whenever the subsystem is mounted.
     */
    status?: string;
}

