/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Number { 
    /**
     * Capable is what the number can carry: any of \"voice\", \"sms\", \"mms\", \"fax\". A number missing \"sms\" cannot send one no matter what this platform does.
     */
    capable?: Array<string>;
    /**
     * Country is the ISO 3166-1 alpha-2 code the number is issued under. Numbering is national, so this is what makes a search answerable at all.
     */
    country?: string;
    /**
     * Currency is the ISO 4217 code Monthly is denominated in. Without it the number beside it means nothing, so the two are always read together.
     */
    currency?: string;
    /**
     * E164 is the number in E.164: a leading + and digits only, no spaces or dashes. That is what a carrier accepts and what a search result must be bought by.
     */
    e164?: string;
    /**
     * ID is the carrier\'s handle for the number, and the id every route here addresses it by. It is not the number itself — see E164.
     */
    id?: string;
    /**
     * Monthly is the recurring rental in the MINOR unit of Currency (cents for USD), exactly as the carrier quoted it. It is a price, not a charge: nothing is billed by this field.
     */
    monthly?: number;
    /**
     * Org is the tenant holding the number. A search result carries none — nobody holds it yet — which is how an available number is told from a held one.
     */
    org?: string;
    /**
     * Type is what kind of number it is: \"local\", \"national\", \"tollfree\" or \"mobile\". It decides both price and what a carrier will let it originate.
     */
    type?: string;
}

