/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yTelemetryFieldKey } from './o11yTelemetryFieldKey';


export interface O11yLabel { 
    key?: O11yTelemetryFieldKey;
    value?: object;
}

