/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yAttributeMapping } from './o11yO11yAttributeMapping';


export interface O11yO11yOIDCConfig { 
    /**
     * ClaimMapping names the token claims to read identity from.
     */
    claimMapping?: O11yO11yAttributeMapping;
    /**
     * ClientID is the OAuth application\'s id.
     */
    clientId?: string;
    /**
     * ClientSecret is the OAuth application\'s secret.
     */
    clientSecret?: string;
    /**
     * GetUserInfo also queries the userinfo endpoint, for providers whose id tokens are thin.
     */
    getUserInfo?: boolean;
    /**
     * InsecureSkipEmailVerified admits addresses the provider has not verified.
     */
    insecureSkipEmailVerified?: boolean;
    /**
     * Issuer is the provider\'s issuer URL.
     */
    issuer?: string;
    /**
     * IssuerAlias overrides the issuer for providers whose discovery document disagrees with their issuer URL.
     */
    issuerAlias?: string;
}

