/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yO11yOperation { 
    /**
     * ErrorCount is how many of those runs errored.
     */
    errorCount?: number;
    /**
     * Name is the operation (span name).
     */
    name?: string;
    /**
     * NumCalls is how many times it ran in the window.
     */
    numCalls?: number;
    /**
     * P50 is its median latency, nanoseconds.
     */
    p50?: number;
    /**
     * P95 is its p95 latency, nanoseconds.
     */
    p95?: number;
    /**
     * P99 is its p99 latency, nanoseconds.
     */
    p99?: number;
}

