/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yLLMUpdatablePricingRule } from './o11yO11yLLMUpdatablePricingRule';


export interface O11yO11yLLMUpdatablePricingRules { 
    /**
     * Rules are the rules to create or update, matched per rule.
     */
    rules?: Array<O11yO11yLLMUpdatablePricingRule>;
}

