/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yAssociatedComponent } from './o11yAssociatedComponent';


export interface O11yMissingMetricsComponentEntry { 
    associatedComponent?: O11yAssociatedComponent;
    documentationLink?: string;
    message?: string;
    metrics?: Array<string>;
}

