/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yQueueFilterKey } from './o11yO11yQueueFilterKey';


export interface O11yO11yQueueFilterRule { 
    /**
     * Key names the attribute the predicate tests.
     */
    key?: O11yO11yQueueFilterKey;
    /**
     * Op is the comparison, e.g. =, !=, in, contains.
     */
    op?: string;
    /**
     * Value is the operand; its JSON type follows the attribute\'s dataType.
     */
    value?: object;
}

