/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yVolumeRecord } from './o11yVolumeRecord';
import { O11yQueryWarnData } from './o11yQueryWarnData';


export interface O11yVolumes { 
    endTimeBeforeRetention?: boolean;
    records?: Array<O11yVolumeRecord>;
    total?: number;
    type?: any | null;
    warning?: O11yQueryWarnData;
}

