/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yO11yDashboardViewData { 
    /**
     * Order is the captured sort direction.
     */
    order?: string;
    /**
     * Query is the captured filter DSL.
     */
    query?: string;
    /**
     * Sort is the captured sort field.
     */
    sort?: string;
    /**
     * Version is the saved-view schema version; must be v1.
     */
    version?: string;
}

