/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yMetricSeriesSet } from './o11yO11yMetricSeriesSet';


export interface O11yO11yMetricInspectOut { 
    /**
     * Data holds the series.
     */
    data?: O11yO11yMetricSeriesSet;
    /**
     * Status is \"success\".
     */
    status?: string;
}

