/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yLLMUser } from './o11yO11yLLMUser';


export interface O11yO11yLLMUsersPage { 
    /**
     * Items are the end users, newest first.
     */
    items?: Array<O11yO11yLLMUser>;
    /**
     * Limit is the page cap the read ran with.
     */
    limit?: number;
    /**
     * Offset is the row offset this page started at.
     */
    offset?: number;
}

