/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yO11yDashboardTag { 
    /**
     * Key is the tag key.
     */
    key?: string;
    /**
     * Value is the tag value.
     */
    value?: string;
}

