/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yQuerybuildertypesv5OrderBy } from './o11yQuerybuildertypesv5OrderBy';
import { O11yGroupByKey } from './o11yGroupByKey';
import { O11yFilter } from './o11yFilter';


export interface O11yPostableClusters { 
    end?: number;
    filter?: O11yFilter;
    groupBy?: Array<O11yGroupByKey>;
    limit?: number;
    offset?: number;
    orderBy?: O11yQuerybuildertypesv5OrderBy;
    start?: number;
}

