/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yQueryEnvelope { 
    /**
     * Spec is the deferred decoding of the query if any.
     */
    spec?: object;
    type?: any | null;
}

