/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yLLMScore } from './o11yO11yLLMScore';


export interface O11yO11yLLMScoresPage { 
    /**
     * Items are the scores, newest first.
     */
    items?: Array<O11yO11yLLMScore>;
    /**
     * Limit is the page cap the read ran with.
     */
    limit?: number;
    /**
     * Offset is the row offset this page started at.
     */
    offset?: number;
    /**
     * Total is how many scores match, across all pages.
     */
    total?: number;
}

