/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yBuilderQuery } from './o11yBuilderQuery';
import { O11yDatastoreQuery } from './o11yDatastoreQuery';
import { O11yQueryEnvelope } from './o11yQueryEnvelope';
import { O11yPromQuery } from './o11yPromQuery';


export interface O11yCompositeQuery { 
    builderQueries?: { [key: string]: O11yBuilderQuery; };
    chQueries?: { [key: string]: O11yDatastoreQuery; };
    /**
     * FillGaps is used to fill the gaps in the time series data
     */
    fillGaps?: boolean;
    panelType?: string;
    promQueries?: { [key: string]: O11yPromQuery; };
    queries?: Array<O11yQueryEnvelope>;
    queryType?: string;
    /**
     * Unit for the time series data shown in the graph This is used in alerts to format the value and threshold
     */
    unit?: string;
}

