/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yCollectedMetric } from './o11yCollectedMetric';
import { O11yCollectedLogAttribute } from './o11yCollectedLogAttribute';


export interface O11yDataCollected { 
    logs?: Array<O11yCollectedLogAttribute>;
    metrics?: Array<O11yCollectedMetric>;
}

