/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11ySpanMapperConfig } from './o11ySpanMapperConfig';


export interface O11yO11ySpanMapperCreateIn { 
    config?: O11ySpanMapperConfig;
    enabled?: boolean;
    fieldContext?: any | null;
    name?: string;
}

