/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yAffectedWidget } from './o11yO11yAffectedWidget';


export interface O11yO11yAffectedAsset { 
    /**
     * ID is the asset\'s id.
     */
    id?: string;
    /**
     * ImpactedLabels are the rule labels the asset uses.
     */
    impactedLabels?: Array<string>;
    /**
     * Name is the asset\'s name.
     */
    name?: string;
    /**
     * Type is dashboard or alert_rule.
     */
    type?: string;
    /**
     * Widget is the affected panel, for a dashboard.
     */
    widget?: O11yO11yAffectedWidget;
}

