/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yFilterSet } from './o11yFilterSet';


export interface O11yO11yRuleHistoryQueryIn { 
    end?: number;
    filters?: O11yFilterSet;
    limit?: number;
    offset?: number;
    order?: string;
    start?: number;
    state?: string;
}

