/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yNotifierConfig } from './o11yNotifierConfig';
import { O11yHTTPClientConfig } from './o11yHTTPClientConfig';


export interface O11yWebexConfig { 
    NotifierConfig?: O11yNotifierConfig;
    api_url?: any | null;
    http_config?: O11yHTTPClientConfig;
    message?: string;
    room_id?: string;
}

