/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yServiceTag } from './o11yO11yServiceTag';


export interface O11yO11yOperationsIn { 
    /**
     * End is the window\'s end, epoch nanoseconds as a string.
     */
    end?: string;
    /**
     * Limit caps how many operations come back.
     */
    limit?: number;
    /**
     * Service is the service whose operations are read.
     */
    service?: string;
    /**
     * Start is the window\'s start, epoch nanoseconds as a string.
     */
    start?: string;
    /**
     * Tags narrow the spans counted, each a span-attribute predicate.
     */
    tags?: Array<O11yO11yServiceTag>;
}

