/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yListMeta } from './o11yListMeta';
import { O11yAnnItemView } from './o11yAnnItemView';


export interface O11yAnnItemList { 
    /**
     * Data is the page of items.
     */
    data?: Array<O11yAnnItemView>;
    /**
     * Meta is the paging that produced it.
     */
    meta?: O11yListMeta;
}

