/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yGlobalConfig } from './o11yO11yGlobalConfig';


export interface O11yO11yGlobalConfigOut { 
    /**
     * Data is the configuration.
     */
    data?: O11yO11yGlobalConfig;
    /**
     * Status is \"success\".
     */
    status?: string;
}

