/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yO11yWidgetQueryRange { 
    data?: any | null;
    meta?: any | null;
    /**
     * Type is the request type the result answers, e.g. time_series, scalar.
     */
    type?: string;
    warning?: any | null;
}

