/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11ySeries { 
    costCents?: number;
    errors?: number;
    requests?: number;
    tokens?: number;
    ts?: string;
}

