/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yFilterSet } from './o11yFilterSet';
import { O11yOrderBy } from './o11yOrderBy';
import { O11yAttributeKey } from './o11yAttributeKey';


export interface O11yProcessListRequest { 
    /**
     * epoch time in ms
     */
    end?: number;
    filters?: O11yFilterSet;
    groupBy?: Array<O11yAttributeKey>;
    limit?: number;
    offset?: number;
    orderBy?: O11yOrderBy;
    /**
     * epoch time in ms
     */
    start?: number;
}

