/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yCreateQueueReq { 
    /**
     * Description is optional free text, up to 512 characters.
     */
    description?: string;
    /**
     * Name is the queue\'s display handle, 1–128 printable characters. It must be unique within the org\'s project. Required.
     */
    name?: string;
    /**
     * ScoreConfigIDs are the eval score-configs reviewers grade against.
     */
    scoreConfigIds?: Array<string>;
}

