/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yMetricSummary } from './o11yO11yMetricSummary';


export interface O11yO11yMetricList { 
    /**
     * Metrics are the metrics, with their metadata.
     */
    metrics?: Array<O11yO11yMetricSummary>;
}

