/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yStatusMaintenance } from './o11yStatusMaintenance';
import { O11yStatusIncident } from './o11yStatusIncident';


export interface O11yStatusSummary { 
    /**
     * CheckedAt is when the underlying availability read was taken, RFC3339 UTC. Not part of the status-page schema the panel parses (which ignores unknown fields); it is here because a status document with no timestamp cannot be told apart from a stale one.
     */
    checked_at?: string;
    in_progress_maintenances?: Array<O11yStatusMaintenance>;
    ongoing_incidents?: Array<O11yStatusIncident>;
    page_title?: string;
    /**
     * PageURL is the HUMAN status page — an HTML page for people, distinct from this JSON endpoint. Every link in this document points there.
     */
    page_url?: string;
    scheduled_maintenances?: Array<O11yStatusMaintenance>;
}

