/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11ySpanMapper } from './o11ySpanMapper';


export interface O11yO11ySpanMapperOut { 
    /**
     * Data is the mapper.
     */
    data?: O11ySpanMapper;
    /**
     * Status is \"success\".
     */
    status?: string;
}

