/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yStatusComponent } from './o11yStatusComponent';


export interface O11yStatusIncident { 
    affected_components?: Array<O11yStatusComponent>;
    /**
     * CurrentWorstImpact is the incident\'s impact on the PLATFORM, which is not the same question as the component\'s own condition above.
     */
    current_worst_impact?: string;
    id?: string;
    /**
     * LastUpdateAt is when the failing measurement this incident reports was read, RFC3339 UTC.
     */
    last_update_at?: string;
    last_update_message?: string;
    name?: string;
    status?: string;
    url?: string;
}

