/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yDaemonSetListResponse } from './o11yDaemonSetListResponse';


export interface O11yO11yDaemonSetListOut { 
    /**
     * Data holds the daemonset records.
     */
    data?: O11yDaemonSetListResponse;
    /**
     * Status is \"success\".
     */
    status?: string;
}

