/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yLimit } from './o11yLimit';


export interface O11yIngestionKey { 
    created_at?: string;
    expires_at?: string;
    id?: string;
    limits?: Array<O11yLimit>;
    name?: string;
    tags?: Array<string>;
    updated_at?: string;
    value?: string;
    workspace_id?: string;
}

