/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yQueryWarningNote } from './o11yO11yQueryWarningNote';


export interface O11yO11yQueryWarning { 
    /**
     * Message is the warning.
     */
    message?: string;
    /**
     * URL points at the relevant documentation.
     */
    url?: string;
    /**
     * Warnings carries additional notes.
     */
    warnings?: Array<O11yO11yQueryWarningNote>;
}

