/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yGCPServiceLogsConfig } from './o11yGCPServiceLogsConfig';
import { O11yGCPServiceMetricsConfig } from './o11yGCPServiceMetricsConfig';


export interface O11yGCPServiceConfig { 
    logs?: O11yGCPServiceLogsConfig;
    metrics?: O11yGCPServiceMetricsConfig;
}

