/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yVariableItem } from './o11yVariableItem';
import { O11yFormatOptions } from './o11yFormatOptions';
import { O11yQuerybuildertypesv5CompositeQuery } from './o11yQuerybuildertypesv5CompositeQuery';


export interface O11yQueryRangeRequest { 
    /**
     * CompositeQuery is the composite query to use for the request.
     */
    compositeQuery?: O11yQuerybuildertypesv5CompositeQuery;
    /**
     * End is the end time of the query in epoch milliseconds.
     */
    end?: number;
    formatOptions?: O11yFormatOptions;
    /**
     * NoCache is a flag to disable caching for the request.
     */
    noCache?: boolean;
    requestType?: any | null;
    /**
     * SchemaVersion is the version of the schema to use for the request payload.
     */
    schemaVersion?: string;
    /**
     * Start is the start time of the query in epoch milliseconds.
     */
    start?: number;
    /**
     * Variables is the variables to use for the request.
     */
    variables?: { [key: string]: O11yVariableItem; };
}

