/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yOrderByKey } from './o11yOrderByKey';


export interface O11yQuerybuildertypesv5OrderBy { 
    direction?: any | null;
    /**
     * key to order by
     */
    key?: O11yOrderByKey;
}

