/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11ySpanMapperGroupCondition } from './o11ySpanMapperGroupCondition';


export interface O11yO11ySpanMapperGroupUpdateIn { 
    condition?: O11ySpanMapperGroupCondition;
    enabled?: boolean;
    name?: string;
}

