/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yNamespaceRecord } from './o11yNamespaceRecord';
import { O11yQueryWarnData } from './o11yQueryWarnData';


export interface O11yNamespaces { 
    endTimeBeforeRetention?: boolean;
    records?: Array<O11yNamespaceRecord>;
    total?: number;
    type?: any | null;
    warning?: O11yQueryWarnData;
}

