/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yProcessListRecord { 
    meta?: { [key: string]: string; };
    processCMD?: string;
    processCMDLine?: string;
    processCPU?: number;
    processID?: string;
    processMemory?: number;
    processName?: string;
}

