/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yAnnItemView } from './o11yAnnItemView';


export interface O11yAnnQueueDetailView { 
    /**
     * CompletedCount is how many have been reviewed.
     */
    completedCount?: number;
    /**
     * CreatedAt is when it was created, RFC3339 in UTC.
     */
    createdAt?: string;
    /**
     * Description is its free text, omitted when empty.
     */
    description?: string;
    /**
     * ID is the queue\'s id.
     */
    id?: string;
    /**
     * Items is the queue\'s first page of items (up to 100).
     */
    items?: Array<O11yAnnItemView>;
    /**
     * Name is its display handle.
     */
    name?: string;
    /**
     * PendingCount is how many of its items are still awaiting review.
     */
    pendingCount?: number;
    /**
     * ScoreConfigIDs are the eval score-configs reviewers grade against.
     */
    scoreConfigIds?: Array<string>;
    /**
     * UpdatedAt is when it last changed, RFC3339 in UTC.
     */
    updatedAt?: string;
}

