/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yLLMRulePricing } from './o11yO11yLLMRulePricing';


export interface O11yO11yLLMUpdatablePricingRule { 
    /**
     * Enabled turns the rule on.
     */
    enabled?: boolean;
    /**
     * ID matches an existing rule by its id.
     */
    id?: string;
    /**
     * IsOverride pins the rule so the sync job skips it. Omit to leave a matched override untouched.
     */
    isOverride?: boolean;
    /**
     * Model is the model the rule prices. Required.
     */
    modelName?: string;
    /**
     * ModelPattern are the model-name globs the rule matches. Required.
     */
    modelPattern?: Array<string>;
    /**
     * Pricing is the per-unit cost. Required.
     */
    pricing?: O11yO11yLLMRulePricing;
    /**
     * Provider is the model\'s provider. Required.
     */
    provider?: string;
    /**
     * SourceID matches an existing rule by its upstream source id.
     */
    sourceId?: string;
    /**
     * Unit is the pricing unit, e.g. per_million_tokens. Required.
     */
    unit?: string;
}

