/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yEvents } from './o11yO11yEvents';


export interface O11yO11yLogsOut { 
    /**
     * Data holds the events.
     */
    data?: O11yO11yEvents;
    /**
     * Status is \"success\".
     */
    status?: string;
}

