/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yO11yDeprecatedUser { 
    /**
     * CreatedAt is when they joined.
     */
    createdAt?: string;
    /**
     * DisplayName is what the console shows for them.
     */
    displayName?: string;
    /**
     * Email is their address.
     */
    email?: string;
    /**
     * ID is the user id.
     */
    id?: string;
    /**
     * IsRoot marks the org\'s root user.
     */
    isRoot?: boolean;
    /**
     * OrgID is the org they belong to.
     */
    orgId?: string;
    /**
     * Role is their legacy role — ADMIN, EDITOR or VIEWER.
     */
    role?: string;
    /**
     * Status is their lifecycle state — active, pending_invite or deleted.
     */
    status?: string;
    /**
     * UpdatedAt is when their record last changed.
     */
    updatedAt?: string;
}

