/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yIntegrationConfigStep } from './o11yIntegrationConfigStep';
import { O11yInstalledIntegration } from './o11yInstalledIntegration';
import { O11yIntegrationConnectionTests } from './o11yIntegrationConnectionTests';
import { O11yIntegrationAuthor } from './o11yIntegrationAuthor';
import { O11yIntegrationAssets } from './o11yIntegrationAssets';
import { O11yDataCollectedForIntegration } from './o11yDataCollectedForIntegration';


export interface O11yIntegration { 
    assets?: O11yIntegrationAssets;
    author?: O11yIntegrationAuthor;
    categories?: Array<string>;
    configuration?: Array<O11yIntegrationConfigStep>;
    connection_tests?: O11yIntegrationConnectionTests;
    data_collected?: O11yDataCollectedForIntegration;
    description?: string;
    icon?: string;
    id?: string;
    installation?: O11yInstalledIntegration;
    overview?: string;
    title?: string;
}

