/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yO11yForgotPasswordIn { 
    /**
     * Email is the address to mail the reset link to. Required.
     */
    email?: string;
    /**
     * FrontendBaseURL is the console origin the reset link is built on.
     */
    frontendBaseURL?: string;
    /**
     * OrgID is the org the address belongs to. Required.
     */
    orgId?: string;
}

