/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yAffectedAsset } from './o11yO11yAffectedAsset';


export interface O11yO11yReductionRulePreview { 
    /**
     * AffectedAssets are the dashboards and alerts the rule would touch.
     */
    affectedAssets?: Array<O11yO11yAffectedAsset>;
    /**
     * CurrentRetainedSeries is how many survive the rules in force today.
     */
    currentRetainedSeries?: number;
    /**
     * DroppedLabels are the labels the rule would drop.
     */
    droppedLabels?: Array<string>;
    /**
     * EffectiveFrom is when the rule would take effect.
     */
    effectiveFrom?: string;
    /**
     * IngestedSeries is how many series the metric ingests today.
     */
    ingestedSeries?: number;
    /**
     * ReductionPercent is the estimated reduction, in percent.
     */
    reductionPercent?: number;
    /**
     * RetainedSeries is how many would survive with the candidate rule.
     */
    retainedSeries?: number;
}

