/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yDaemonSetListRecord { 
    availableNodes?: number;
    cpuLimit?: number;
    cpuRequest?: number;
    cpuUsage?: number;
    daemonSetName?: string;
    desiredNodes?: number;
    memoryLimit?: number;
    memoryRequest?: number;
    memoryUsage?: number;
    meta?: { [key: string]: string; };
    restarts?: number;
}

