/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yStorableIntegrationDashboard } from './o11yStorableIntegrationDashboard';


export interface O11yServiceDashboard { 
    description?: string;
    integrationDashboard?: O11yStorableIntegrationDashboard;
    title?: string;
}

