/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface O11yUser { 
    createdAt?: string;
    displayName?: string;
    email?: any | null;
    id?: any | null;
    isRoot?: boolean;
    orgId?: any | null;
    status?: any | null;
    updatedAt?: string;
}

