/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yAgentReport } from './o11yAgentReport';
import { O11yAccountConfig } from './o11yAccountConfig';


export interface O11yAccount { 
    agentReport?: O11yAgentReport;
    config?: O11yAccountConfig;
    createdAt?: string;
    id?: any | null;
    orgId?: any | null;
    provider?: any | null;
    providerAccountId?: string;
    removedAt?: string;
    updatedAt?: string;
}

