/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yDashboardView } from './o11yO11yDashboardView';


export interface O11yO11yDashboardViewOut { 
    /**
     * Data is the saved view.
     */
    data?: O11yO11yDashboardView;
    /**
     * Status is \"success\".
     */
    status?: string;
}

