/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { O11yO11yCallbackAuthN } from './o11yO11yCallbackAuthN';
import { O11yO11yPasswordAuthN } from './o11yO11yPasswordAuthN';


export interface O11yO11yAuthNSupport { 
    /**
     * Callback are the SSO routes; each is begun by visiting its URL.
     */
    callback?: Array<O11yO11yCallbackAuthN>;
    /**
     * Password are the password routes.
     */
    password?: Array<O11yO11yPasswordAuthN>;
}

