/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Offer { 
    /**
     * whether it can be bought right now
     */
    available?: boolean;
    /**
     * the currency both prices are in
     */
    currency?: string;
    /**
     * the name this quote prices
     */
    domain?: string;
    /**
     * whether the registry prices it above the standard rate
     */
    premium?: boolean;
    /**
     * sell (first-term registration)
     */
    priceCents?: number;
    /**
     * sell (renewal)
     */
    renewalPriceCents?: number;
    /**
     * the top-level domain the name sits under
     */
    tld?: string;
}

