/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OpenaiUsage } from './openaiUsage';
import { OpenaiEmbedding } from './openaiEmbedding';


export interface OpenaiEmbeddingResponse { 
    data?: Array<OpenaiEmbedding>;
    model?: string;
    object?: string;
    usage?: OpenaiUsage;
}

