/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrgEarningView { 
    /**
     * CommissionCents is what the caller earned from that org across ALL periods, in cents. Deliberately the caller\'s own share and nothing else: that org\'s spend and the margin on it are not restated here.
     */
    commissionCents?: number;
    /**
     * ReferredOrg is the org slug this contribution came from — one the caller referred, directly or up to three levels down.
     */
    referredOrg?: string;
}

