/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceStatus } from './sourceStatus';


export interface OverviewData { 
    activeProducts?: number;
    creditsCents?: number;
    drift?: number;
    lastSync?: string;
    orgs?: number;
    products?: number;
    sources?: Array<SourceStatus>;
    spendCents30d?: number;
    tokens30d?: number;
    users?: number;
}

