/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchApplicationIn { 
    /**
     * ID is the application to move, from the path.
     */
    id?: string;
    /**
     * Note is a free-text comment recorded on the timeline, with or without a stage change.
     */
    note?: string;
    /**
     * Reason records WHY, and is required to reject.
     */
    reason?: string;
    /**
     * Stage is the stage to move to: applied, screened, qualified, credits-offered, onboarded or rejected. Omit to leave the stage alone.
     */
    stage?: string;
}

