/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PayoutData } from './payoutData';


export interface PayoutResult { 
    /**
     * Data carries the payout and the author.
     */
    data?: PayoutData;
    /**
     * Msg is the envelope\'s message slot, empty on success.
     */
    msg?: string;
    /**
     * Status is \"ok\".
     */
    status?: string;
}

