/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PnLLine } from './pnLLine';


export interface PnL { 
    expense?: Array<PnLLine>;
    from?: string;
    income?: Array<PnLLine>;
    /**
     * TotalIncome − TotalExpense
     */
    netIncome?: number;
    to?: string;
    totalExpense?: number;
    totalIncome?: number;
}

