/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PricingPlanList { 
    /**
     * Plans are the plans in this section, each an opaque object exactly as the pricing source emits it — typically id, name, description, price and a feature list.
     */
    plans?: Array<{ [key: string]: object; }>;
}

