/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScreenResult } from './screenResult';
import { StageEvent } from './stageEvent';


export interface ProgramApplication { 
    /**
     * Company is the applicant\'s company name.
     */
    company?: string;
    /**
     * CompanyID is the CRM Company minted for this lead at intake, so the startup also appears in the org\'s standard CRM tabs. Empty when that best-effort projection did not run.
     */
    companyId?: string;
    /**
     * ContactID is the CRM Contact minted for this lead at intake. Empty when that best-effort projection did not run.
     */
    contactId?: string;
    /**
     * ContactName is the person who applied.
     */
    contactName?: string;
    /**
     * CreatedAt is the unix second the application arrived. Server-owned.
     */
    createdAt?: number;
    /**
     * Email is the applicant\'s email — half of the (email, company) key a resubmission refreshes instead of duplicating.
     */
    email?: string;
    /**
     * Events is the append-only stage-transition log, oldest first.
     */
    events?: Array<StageEvent>;
    /**
     * ID is the server-minted application id (\"appl_\" + 128 random bits).
     */
    id?: string;
    /**
     * Metadata is the FULL submitted form, every field, including the arrays the promoted columns above do not carry (tier1Investors, useCases) and the deterministic tier1Matched list.
     */
    metadata?: { [key: string]: object; };
    /**
     * Reason is why the application was rejected, required to reject. Empty otherwise.
     */
    reason?: string;
    /**
     * Role is the applicant\'s role at their company.
     */
    role?: string;
    /**
     * Screen is the AI screen. It runs after intake, so a freshly created application carries a \"pending\" screen.
     */
    screen?: ScreenResult;
    /**
     * Stage is the pipeline stage: applied, screened, qualified, credits-offered, onboarded or rejected. Server-owned — it starts at \"applied\" and moves only through the transition machine.
     */
    stage?: string;
    /**
     * Tier1 is whether the applicant is tier-1 backed, derived deterministically at intake from the submitted fund list — independent of the AI screen.
     */
    tier1?: boolean;
    /**
     * UpdatedAt is the unix second of the last write. Server-owned.
     */
    updatedAt?: number;
    /**
     * Website is the applicant\'s website as submitted.
     */
    website?: string;
}

