/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Repo relinks the git source. Absent leaves the existing link.
 */
export interface ProjectsUpdateRepo { 
    branch?: string;
    url?: string;
}

