/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PropSpec { 
    description?: string;
    displayName?: string;
    name?: string;
    required?: boolean;
    /**
     * string|number|boolean|object|array
     */
    type?: string;
}

