/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProviderRow { 
    /**
     * CostCents is what they cost the org, in US cents.
     */
    costCents?: number;
    /**
     * Provider is the upstream the requests were routed to, e.g. anthropic.
     */
    provider?: string;
    /**
     * Requests is how many completions the org made against that provider.
     */
    requests?: number;
    /**
     * Tokens is the total tokens those completions consumed, prompt plus completion.
     */
    tokens?: number;
}

