/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Question { 
    account?: string;
    /**
     * formatted figure ($…)
     */
    amount?: string;
    /**
     * the source transaction id it concerns
     */
    id?: string;
    /**
     * outlier|reversal|roundoff|uncosted|overdrawn
     */
    kind?: string;
    postedAt?: string;
    /**
     * the specific question to ask the founder
     */
    text?: string;
}

