/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Offer } from './offer';


export interface QuoteList { 
    /**
     * Results is one quote per name, priced RETAIL — this deployment\'s markup is already applied and the wholesale cost is never on the wire.
     */
    results?: Array<Offer>;
}

