/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReindexOut { 
    /**
     * Failed is how many documents could not be embedded; each is logged with its name, and the rest of the rebuild went on without it.
     */
    failed?: number;
    /**
     * Lexical is how many rows the org\'s lexical index holds now; 0 in a deployment without the index app.
     */
    lexical?: number;
    /**
     * Removed is how many rows the lexical index held for documents that no longer exist; 0 without the index app.
     */
    removed?: number;
    /**
     * Vectors is how many documents were embedded and written to the org\'s collection, which was dropped and created again at the configured size.
     */
    vectors?: number;
}

