/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Responsible { 
    /**
     * Country is where they reside, ISO 3166-1 alpha-2.
     */
    country?: string;
    /**
     * Email reaches them for signature.
     */
    email?: string;
    /**
     * Name is their full legal name as the IRS will hold it.
     */
    name?: string;
    /**
     * USTaxID reports that they hold an SSN or ITIN. It is a BOOLEAN on purpose: the number itself is never needed here and a field that could hold it is a field that will eventually be logged.
     */
    usTaxId?: boolean;
}

