/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RiskLabelFact } from './riskLabelFact';


export interface RiskLabelIn { 
    /**
     * Labels is the batch. Each member is judged on its own: one refusal does not discard the rest, because a webhook redelivering five disputes must not lose four of them to one malformed fifth.
     */
    labels?: Array<RiskLabelFact>;
}

