/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoundInput { 
    /**
     * Name is the round\'s name on the cap table, e.g. \"Seed\". Required.
     */
    name?: string;
    /**
     * PreMoneyValuation is the valuation the round prices off, before the new money.
     */
    preMoneyValuation?: number;
    /**
     * PricePerShare is the per-share price of a priced round.
     */
    pricePerShare?: number;
    /**
     * RoundType is PRICED, SAFE or CONVERTIBLE_NOTE. Defaults to PRICED.
     */
    roundType?: string;
    /**
     * ShareClassID is the cap table\'s share class the round issues into.
     */
    shareClassId?: string;
    /**
     * TargetAmount is the amount the round is raising, recorded verbatim on the canonical cap table\'s rounds.create contract.
     */
    targetAmount?: number;
}

