/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RouteCreateIn { 
    /**
     * Pattern is the URL pattern to bind, e.g. \"acme.com/api/_*\".
     */
    pattern?: string;
    /**
     * Script is the Worker script to dispatch to. Omit it to leave the pattern bound to no script, which is how Cloudflare expresses \"bypass the Worker here\".
     */
    script?: string;
    /**
     * Zone is the 32-hex Cloudflare zone id, from the path.
     */
    zone?: string;
}

