/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnvVarJSON } from './envVarJSON';


export interface RunReq { 
    /**
     * Env is the run\'s environment. Keys must match `^[A-Za-z_][A-Za-z0-9_]*$`; a variable marked `secret: true` is sealed into KMS.
     */
    env?: Array<EnvVarJSON>;
    /**
     * GPU is how many GPUs the run asks for; a negative value is 400.
     */
    gpu?: number;
    /**
     * Image is the container image to run. Required.
     */
    image?: string;
    /**
     * MaxScale above the floor declares an autoscaling ceiling; 0 means no autoscaler at all — a fixed run at the floor.
     */
    maxScale?: number;
    /**
     * MinScale is the replica floor, clamped to the deployment\'s limit.
     */
    minScale?: number;
    /**
     * Name is the run\'s name, and the slug is derived from it. Required, and it must resolve to `^[a-z0-9]([a-z0-9-]{0,38}[a-z0-9])?$`. Re-running the same name updates that run in place.
     */
    name?: string;
    /**
     * Port is the container port the run listens on.
     */
    port?: number;
    /**
     * Runtime is accepted for the client contract and echoed nowhere: the image IS the runtime unit.
     */
    runtime?: string;
    /**
     * Shape is a compute size label, echoed back; sizing is the operator\'s default. Defaults to \"auto\".
     */
    shape?: string;
}

