/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SaaSPlan { 
    active?: number;
    category?: string;
    mrrCents?: number;
    name?: string;
    plan?: string;
    seats?: number;
    trialing?: number;
}

