/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SafeProposal { 
    /**
     * R is the r component of the MPC threshold signature over the Safe-tx hash.
     */
    r?: string;
    /**
     * S is the s component of that signature.
     */
    s?: string;
    /**
     * SafeAddress is the Safe contract this transaction is for.
     */
    safeAddress?: string;
    /**
     * SafeTxHash is the EIP-712 Safe transaction hash, bound to the Safe contract and the chain id — the value the owner approval signs.
     */
    safeTxHash?: string;
    /**
     * WalletID is the wallet whose Safe this is.
     */
    walletId?: string;
}

