/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SbomIngested { 
    /**
     * ComponentCount is how many components the CycloneDX document yielded and this call persisted.
     */
    componentCount?: number;
    /**
     * ImageDigest is the content-addressed digest the components were keyed under.
     */
    imageDigest?: string;
}

