/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduleInput { 
    /**
     * ID is the campaign id from the path.
     */
    id?: string;
    /**
     * ScheduledAt is the unix send time. 0 clears the schedule.
     */
    scheduledAt?: number;
}

