/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecretView } from './secretView';


export interface SecretList { 
    /**
     * Secrets is one row per distinct (namespace, name) a function mounts. Values are NEVER read or returned.
     */
    secrets?: Array<SecretView>;
}

