/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeoMetric } from './seoMetric';


export interface SeoIdeaOut { 
    /**
     * Cost is what this call cost, in USD, as an exact decimal string.
     */
    cost?: string;
    /**
     * Keywords is the phrases found, each measured.
     */
    keywords?: Array<SeoMetric>;
    /**
     * Total is how many the upstream holds, which is usually more than Limit returned — it is what raising the limit would reach.
     */
    total?: number;
}

