/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SourceStatus { 
    at?: string;
    error?: string;
    name?: string;
    ok?: boolean;
    rows?: number;
}

