/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategorySpend } from './categorySpend';
import { SpendPoint } from './spendPoint';


export interface Spend { 
    /**
     * Available is false when the commerce ledger was unconfigured or unreachable. Every number below is then an honest zero, NOT a measured one.
     */
    available?: boolean;
    /**
     * AvailableCents is what of that balance is still spendable.
     */
    availableCents?: number;
    /**
     * BalanceCents is the prepaid wallet\'s balance, in US cents.
     */
    balanceCents?: number;
    /**
     * ByCategory is the window\'s spend split by ledger category, largest first.
     */
    byCategory?: Array<CategorySpend>;
    /**
     * MTDCents is commerce\'s authoritative month-to-date consumed figure, which is a different period from the window and is not derived from it.
     */
    mtdCents?: number;
    /**
     * OverageCents is month-to-date consumption beyond the plan\'s allowance.
     */
    overageCents?: number;
    /**
     * Series is the window\'s spend over time, gap-filled at the window\'s interval.
     */
    series?: Array<SpendPoint>;
    /**
     * Source names where the roll-up came from.
     */
    source?: string;
    /**
     * TotalCents is consumption over the requested window, in US cents. It is self-consistent with ByCategory and Series.
     */
    totalCents?: number;
}

