/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Step { 
    /**
     * Body is the message text. Required. The signed one-click unsubscribe link is appended to it at send time.
     */
    body?: string;
    /**
     * CreatedAt is unix seconds, server-assigned.
     */
    createdAt?: number;
    /**
     * DelaySeconds is how long after the previous step this one sends (after enrollment, for step 0).
     */
    delaySeconds?: number;
    /**
     * ID is the server-assigned step id (\"step_\" + 128 random bits).
     */
    id?: string;
    /**
     * Idx is the step\'s 0-based position, assigned by appending: a new step always lands after the last one.
     */
    idx?: number;
    /**
     * SequenceID is the sequence this step belongs to.
     */
    sequenceId?: string;
    /**
     * Subject is the email subject line, capped at 1024 bytes.
     */
    subject?: string;
}

