/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Subject { 
    createdAt?: number;
    email?: string;
    id?: string;
    kind?: string;
    name?: string;
    org?: string;
    /**
     * the org\'s own opaque external id for this subject
     */
    ref?: string;
    updatedAt?: number;
}

