/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Reach } from './reach';
import { Precompile } from './precompile';


export interface Survey { 
    /**
     * Carries is all four where the node answered and `null` where it did not. It is never a short list: a partial read reporting three would let a reader count them and conclude the chain is missing one.
     */
    carries?: Array<Precompile>;
    chain?: string;
    reach?: Reach;
    /**
     * RPC is the endpoint that was asked, so an answer names where it came from.
     */
    rpc?: string;
}

