/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SweepResult { 
    /**
     * Qualified is how many of those referrals qualified on this pass.
     */
    qualified?: number;
    /**
     * Swept is how many pending referrals were checked.
     */
    swept?: number;
}

