/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SyncTally { 
    /**
     * Live is the number of vouchers newly posted to the live ledger.
     */
    live?: number;
    /**
     * Sandbox is the number newly posted to the sandbox ledger.
     */
    sandbox?: number;
}

