/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TariffIn { 
    /**
     * AgentOfRecord puts us on file as the entity\'s agent, yearly.
     */
    agentOfRecord?: boolean;
    /**
     * ExpeditedEIN prioritises the EIN.
     */
    expeditedEin?: boolean;
    /**
     * Jurisdiction is the state of formation.
     */
    jurisdiction?: string;
    /**
     * Structure is the entity being formed: c-corp, llc or dao-llc.
     */
    structure?: string;
}

