/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TraceView } from './traceView';


export interface TraceList { 
    /**
     * Data is the caller org\'s traces matching the filters, bounded by limit.
     */
    data?: Array<TraceView>;
}

