/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionView } from './sessionView';


export interface TreeNode { 
    children?: Array<TreeNode>;
    session?: SessionView;
}

