/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrustDecision { 
    /**
     * Days is how long the grant stays open, from now. Optional; 14 by default and 365 at most — a longer release is describing a customer relationship rather than a document.
     */
    days?: number;
    /**
     * ID is the request to answer, taken from the path.
     */
    id?: string;
    /**
     * Note is why. Recorded on the request either way, and it is what the record shows a year later.
     */
    note?: string;
}

