/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrustPublish { 
    /**
     * Attester is who vouched for it: \"self\" for anything the org states itself, or \"auditor\" for anything an independent auditor put their name to. REQUIRED, and anything other than \"self\" is read as \"auditor\" — the safe direction, since an auditor-signed item can only ever be released on request.
     */
    attester?: string;
    /**
     * Body is the item\'s content for the kinds that are text rather than a file: an article, a subprocessor entry, a dated note.
     */
    body?: string;
    /**
     * Document is a data-room document holding the item\'s bytes, uploaded first through POST /v1/dataroom/documents. Optional: an item can be content with no file. The document must already exist in the caller org\'s own store.
     */
    document?: string;
    /**
     * Framework is the standard it speaks to. Optional and free text — the value is the org\'s own, not a list this API keeps.
     */
    framework?: string;
    /**
     * Kind is what the item is: report, letter, policy, questionnaire, subprocessor, article or update. Required.
     */
    kind?: string;
    /**
     * Name is the item\'s title. Required.
     */
    name?: string;
    /**
     * Summary is a line about it. Optional.
     */
    summary?: string;
    /**
     * Tier is who may read it: \"public\" or \"gated\". It DEFAULTS TO GATED and anything that is not exactly \"public\" is gated, so an item published by a caller that says nothing is private and someone has to release it on purpose. \"public\" is refused for an auditor-signed item.
     */
    tier?: string;
}

