/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrustItem } from './trustItem';


export interface TrustPage { 
    /**
     * Items is everything the centre publishes: what can be read now, and what exists and is released on request.
     */
    items?: Array<TrustItem>;
    /**
     * Name is the org\'s display name for its centre.
     */
    name?: string;
    /**
     * Nda is the text a party must accept to ask for the gated items, verbatim. Empty when the org asks for none.
     */
    nda?: string;
    /**
     * Slug is the centre\'s public address.
     */
    slug?: string;
}

