/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsagePoint { 
    /**
     * Requests is how many LLM calls fell in this bucket.
     */
    requests?: number;
    /**
     * SpendCents is what they cost, in cents.
     */
    spendCents?: number;
    /**
     * T is the bucket\'s start, RFC3339 UTC, aligned to the interval.
     */
    t?: string;
    /**
     * Tokens is prompt plus completion tokens over those calls.
     */
    tokens?: number;
}

