/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VerificationReq { 
    /**
     * Email is an inline subject\'s contact email, sealed at rest.
     */
    email?: string;
    /**
     * Kind is an inline subject\'s party type: \"individual\" (KYC) or \"business\" (KYB).
     */
    kind?: string;
    /**
     * Name is an inline subject\'s name, sealed at rest.
     */
    name?: string;
    /**
     * Ref is the org\'s own opaque external id for an inline subject.
     */
    ref?: string;
    /**
     * SubjectID names an existing subject to verify; empty creates one inline.
     */
    subjectId?: string;
}

