/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Wallet } from './wallet';


export interface WalletList { 
    /**
     * Wallets are the matching wallets, newest first.
     */
    wallets?: Array<Wallet>;
}

