/**
 * Hanzo Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WebOverview { 
    /**
     * Available is false when the product-event table could not be read — the lens is reported missing rather than as zeros that look like real traffic.
     */
    available?: boolean;
    /**
     * Pageviews is how many $pageview events landed in the window.
     */
    pageviews?: number;
    /**
     * Reason says why the lens is unavailable. Omitted when it is available.
     */
    reason?: string;
    /**
     * Sessions is how many distinct visits they span.
     */
    sessions?: number;
    /**
     * Source is the warehouse table the lens read.
     */
    source?: string;
    /**
     * Visitors is how many distinct people those pageviews came from.
     */
    visitors?: number;
}

